### ISSUE TITLE
Apartado 1: Introducción y metas

### ISSUE THREAD

**Issue by uo245020** [Arquisoft/radarin_es2a#1]

**Comment by UO250825** [comment]
¿Creéis que los siguientes requisitos serían funcionales? 

- Compatibilidad con SOLID

- El sistema será desplegable usando Docker además de ser desplegada en la nube (Heroku).

- Pruebas unitarias automáticas aceptación + carga (Integración continua)

**Comment by UO250825** [comment]
Hecha
