### ISSUE TITLE
Solucionar problemas heroku

### ISSUE THREAD

**Issue by uo245020** [Arquisoft/radarin_es2a#112]
No se redirigen bien las peticiones ni se muestran bien los formularios de iniciar sesión y registrarse.

**Comment by UO264423** [comment]
No se puede navegar dentro de la aplicacion. Se pregunta en el foro de dudas de la asignatura

**Comment by UO264423** [comment]
La pregunta fue resuelta en el foro de la asignatura, @uo245020 la integro en #176
