### ISSUE TITLE
Incluir en el glosario la definición de Gestor de POD

### ISSUE THREAD

**Issue by UO263918** [Arquisoft/radarin_es2a#46]
Incluir la definición de Gestor de POD en el glosario ya que no se explica correctamente en el proyecto.

**Comment by uo271314** [comment]
Se ha decidido eliminar el gestor del POD, puesto que no se ve necesario el uso de una figura externa para trabajar sobre el POD.
Se ha eliminado tanto del glosario como de la arquitectura de bloques del apartado 5.
