### ISSUE TITLE
BÚSQUEDA DE INFORMACIÓN ACERCA DE REACT-NATIVE

### ISSUE THREAD

**Issue by uo258427** [Arquisoft/radarin_es2a#58]

**Comment by uo258427** [comment]
Después de haber buscado cierta información sobre el framework React-Native, la que se ha considerado más relevante para tener en cuenta ha sido la siguiente:
"Instalación de react-native e inicialización de un proyecto"
https://youtu.be/NdwghbFNITY
"Tutoriales acerca de react-native"
https://youtube.com/playlist?list=PLUlw6638d2QZFbQfC3sB5mKWJUWr2HEkc

**Comment by UO250825** [comment]
Se puede encontrar más  documentación en la wiki del proyecto, en la página "[Recursos de aprendiazaje](https://github.com/Arquisoft/radarin_es2a/wiki/Recursos-de-aprendizaje)".
